site_name: ArdorQuery
site_author: 'Roman Vladimirov'
docs_dir: docs/
repo_name: 'trueromanus/ArdorQuery'
repo_url: 'https://github.com/trueromanus/ArdorQuery'
nav:
  - Home: index.md
  - Getting started: basicshortcuts.md
  - Basic fields: commonfields.md
  - Field aliases: fieldaliases.md
  - Options: options.md
  - Scripting: postscript.md
  - Global Variables: globalvariables.md
