name: Build on macOS

on:
  push:
    branches: []

jobs:
  build:

    runs-on: macos-12

    steps:
    - uses: actions/checkout@v3
    - name: Install Qt dependencies
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.5.3
        cache: true
        modules: 'qtscxml qt5compat qtshadertools qtimageformats qtwebsockets'
    - name: run qmake
      run: qmake6 -makefile -o src/Makefile src/ArdorQuery.pro
    - name: run make
      run: make -C src
    - uses: actions/upload-artifact@v3
      with:
        path: ArdorQuery.app
